// International countries data with provinces/states/regions
// Supports South Africa, USA, China, and more

export interface Country {
  code: string;
  name: string;
  regions: Region[];
  currency: string;
  currencySymbol: string;
}

export interface Region {
  id: string;
  name: string;
}

export const COUNTRIES: Record<string, Country> = {
  ZA: {
    code: 'ZA',
    name: 'South Africa',
    currency: 'ZAR',
    currencySymbol: 'R',
    regions: [
      { id: 'eastern-cape', name: 'Eastern Cape' },
      { id: 'free-state', name: 'Free State' },
      { id: 'gauteng', name: 'Gauteng' },
      { id: 'kwazulu-natal', name: 'KwaZulu-Natal' },
      { id: 'limpopo', name: 'Limpopo' },
      { id: 'mpumalanga', name: 'Mpumalanga' },
      { id: 'north-west', name: 'North West' },
      { id: 'northern-cape', name: 'Northern Cape' },
      { id: 'western-cape', name: 'Western Cape' },
    ],
  },
  US: {
    code: 'US',
    name: 'United States',
    currency: 'USD',
    currencySymbol: '$',
    regions: [
      { id: 'alabama', name: 'Alabama' },
      { id: 'alaska', name: 'Alaska' },
      { id: 'arizona', name: 'Arizona' },
      { id: 'arkansas', name: 'Arkansas' },
      { id: 'california', name: 'California' },
      { id: 'colorado', name: 'Colorado' },
      { id: 'connecticut', name: 'Connecticut' },
      { id: 'delaware', name: 'Delaware' },
      { id: 'florida', name: 'Florida' },
      { id: 'georgia', name: 'Georgia' },
      { id: 'hawaii', name: 'Hawaii' },
      { id: 'idaho', name: 'Idaho' },
      { id: 'illinois', name: 'Illinois' },
      { id: 'indiana', name: 'Indiana' },
      { id: 'iowa', name: 'Iowa' },
      { id: 'kansas', name: 'Kansas' },
      { id: 'kentucky', name: 'Kentucky' },
      { id: 'louisiana', name: 'Louisiana' },
      { id: 'maine', name: 'Maine' },
      { id: 'maryland', name: 'Maryland' },
      { id: 'massachusetts', name: 'Massachusetts' },
      { id: 'michigan', name: 'Michigan' },
      { id: 'minnesota', name: 'Minnesota' },
      { id: 'mississippi', name: 'Mississippi' },
      { id: 'missouri', name: 'Missouri' },
      { id: 'montana', name: 'Montana' },
      { id: 'nebraska', name: 'Nebraska' },
      { id: 'nevada', name: 'Nevada' },
      { id: 'new-hampshire', name: 'New Hampshire' },
      { id: 'new-jersey', name: 'New Jersey' },
      { id: 'new-mexico', name: 'New Mexico' },
      { id: 'new-york', name: 'New York' },
      { id: 'north-carolina', name: 'North Carolina' },
      { id: 'north-dakota', name: 'North Dakota' },
      { id: 'ohio', name: 'Ohio' },
      { id: 'oklahoma', name: 'Oklahoma' },
      { id: 'oregon', name: 'Oregon' },
      { id: 'pennsylvania', name: 'Pennsylvania' },
      { id: 'rhode-island', name: 'Rhode Island' },
      { id: 'south-carolina', name: 'South Carolina' },
      { id: 'south-dakota', name: 'South Dakota' },
      { id: 'tennessee', name: 'Tennessee' },
      { id: 'texas', name: 'Texas' },
      { id: 'utah', name: 'Utah' },
      { id: 'vermont', name: 'Vermont' },
      { id: 'virginia', name: 'Virginia' },
      { id: 'washington', name: 'Washington' },
      { id: 'west-virginia', name: 'West Virginia' },
      { id: 'wisconsin', name: 'Wisconsin' },
      { id: 'wyoming', name: 'Wyoming' },
    ],
  },
  CN: {
    code: 'CN',
    name: 'China',
    currency: 'CNY',
    currencySymbol: '¥',
    regions: [
      { id: 'beijing', name: 'Beijing' },
      { id: 'shanghai', name: 'Shanghai' },
      { id: 'guangdong', name: 'Guangdong' },
      { id: 'zhejiang', name: 'Zhejiang' },
      { id: 'jiangsu', name: 'Jiangsu' },
      { id: 'sichuan', name: 'Sichuan' },
      { id: 'hubei', name: 'Hubei' },
      { id: 'fujian', name: 'Fujian' },
      { id: 'shandong', name: 'Shandong' },
      { id: 'henan', name: 'Henan' },
      { id: 'hunan', name: 'Hunan' },
      { id: 'anhui', name: 'Anhui' },
      { id: 'hebei', name: 'Hebei' },
      { id: 'shanxi', name: 'Shanxi' },
      { id: 'liaoning', name: 'Liaoning' },
      { id: 'jilin', name: 'Jilin' },
      { id: 'heilongjiang', name: 'Heilongjiang' },
      { id: 'jiangxi', name: 'Jiangxi' },
      { id: 'guangxi', name: 'Guangxi' },
      { id: 'guizhou', name: 'Guizhou' },
      { id: 'yunnan', name: 'Yunnan' },
      { id: 'gansu', name: 'Gansu' },
      { id: 'shaanxi', name: 'Shaanxi' },
      { id: 'qinghai', name: 'Qinghai' },
      { id: 'tibet', name: 'Tibet' },
      { id: 'ningxia', name: 'Ningxia' },
      { id: 'xinjiang', name: 'Xinjiang' },
      { id: 'hainan', name: 'Hainan' },
      { id: 'chongqing', name: 'Chongqing' },
      { id: 'tianjin', name: 'Tianjin' },
      { id: 'inner-mongolia', name: 'Inner Mongolia' },
      { id: 'macau', name: 'Macau' },
      { id: 'hong-kong', name: 'Hong Kong' },
    ],
  },
  GB: {
    code: 'GB',
    name: 'United Kingdom',
    currency: 'GBP',
    currencySymbol: '£',
    regions: [
      { id: 'england', name: 'England' },
      { id: 'scotland', name: 'Scotland' },
      { id: 'wales', name: 'Wales' },
      { id: 'northern-ireland', name: 'Northern Ireland' },
    ],
  },
  NG: {
    code: 'NG',
    name: 'Nigeria',
    currency: 'NGN',
    currencySymbol: '₦',
    regions: [
      { id: 'lagos', name: 'Lagos' },
      { id: 'abuja', name: 'Abuja Federal Capital Territory' },
      { id: 'rivers', name: 'Rivers' },
      { id: 'kaduna', name: 'Kaduna' },
      { id: 'kano', name: 'Kano' },
      { id: 'oyo', name: 'Oyo' },
      { id: 'enugu', name: 'Enugu' },
      { id: 'delta', name: 'Delta' },
      { id: 'edo', name: 'Edo' },
      { id: 'imo', name: 'Imo' },
    ],
  },
  KE: {
    code: 'KE',
    name: 'Kenya',
    currency: 'KES',
    currencySymbol: 'KSh',
    regions: [
      { id: 'nairobi', name: 'Nairobi' },
      { id: 'mombasa', name: 'Mombasa' },
      { id: 'kisumu', name: 'Kisumu' },
      { id: 'nakuru', name: 'Nakuru' },
      { id: 'eldoret', name: 'Eldoret' },
    ],
  },
  DE: {
    code: 'DE',
    name: 'Germany',
    currency: 'EUR',
    currencySymbol: '€',
    regions: [
      { id: 'bavaria', name: 'Bavaria' },
      { id: 'berlin', name: 'Berlin' },
      { id: 'hamburg', name: 'Hamburg' },
      { id: 'hesse', name: 'Hesse' },
      { id: 'north-rhine', name: 'North Rhine-Westphalia' },
      { id: 'baden-wurttemberg', name: 'Baden-Württemberg' },
      { id: 'saxony', name: 'Saxony' },
    ],
  },
  FR: {
    code: 'FR',
    name: 'France',
    currency: 'EUR',
    currencySymbol: '€',
    regions: [
      { id: 'ile-de-france', name: 'Île-de-France' },
      { id: 'auvergne-rhone', name: 'Auvergne-Rhône-Alpes' },
      { id: 'nouvelle-aquitaine', name: 'Nouvelle-Aquitaine' },
      { id: 'occitanie', name: 'Occitanie' },
      { id: 'provence', name: 'Provence-Alpes-Côte d\'Azur' },
    ],
  },
  JP: {
    code: 'JP',
    name: 'Japan',
    currency: 'JPY',
    currencySymbol: '¥',
    regions: [
      { id: 'tokyo', name: 'Tokyo' },
      { id: 'osaka', name: 'Osaka' },
      { id: 'kyoto', name: 'Kyoto' },
      { id: 'hokkaido', name: 'Hokkaido' },
      { id: 'fukuoka', name: 'Fukuoka' },
      { id: 'aichi', name: 'Aichi' },
      { id: 'kanagawa', name: 'Kanagawa' },
    ],
  },
  AU: {
    code: 'AU',
    name: 'Australia',
    currency: 'AUD',
    currencySymbol: 'A$',
    regions: [
      { id: 'nsw', name: 'New South Wales' },
      { id: 'victoria', name: 'Victoria' },
      { id: 'queensland', name: 'Queensland' },
      { id: 'western-australia', name: 'Western Australia' },
      { id: 'south-australia', name: 'South Australia' },
    ],
  },
  CA: {
    code: 'CA',
    name: 'Canada',
    currency: 'CAD',
    currencySymbol: 'C$',
    regions: [
      { id: 'ontario', name: 'Ontario' },
      { id: 'quebec', name: 'Quebec' },
      { id: 'british-columbia', name: 'British Columbia' },
      { id: 'alberta', name: 'Alberta' },
      { id: 'manitoba', name: 'Manitoba' },
    ],
  },
  IN: {
    code: 'IN',
    name: 'India',
    currency: 'INR',
    currencySymbol: '₹',
    regions: [
      { id: 'maharashtra', name: 'Maharashtra' },
      { id: 'karnataka', name: 'Karnataka' },
      { id: 'tamil-nadu', name: 'Tamil Nadu' },
      { id: 'uttar-pradesh', name: 'Uttar Pradesh' },
      { id: 'delhi', name: 'Delhi' },
      { id: 'gujarat', name: 'Gujarat' },
      { id: 'kerala', name: 'Kerala' },
      { id: 'west-bengal', name: 'West Bengal' },
    ],
  },
  BR: {
    code: 'BR',
    name: 'Brazil',
    currency: 'BRL',
    currencySymbol: 'R$',
    regions: [
      { id: 'sao-paulo', name: 'São Paulo' },
      { id: 'rio-de-janeiro', name: 'Rio de Janeiro' },
      { id: 'minas-gerais', name: 'Minas Gerais' },
      { id: 'bahia', name: 'Bahia' },
      { id: 'distrito-federal', name: 'Distrito Federal' },
    ],
  },
};

export const COUNTRY_LIST = Object.values(COUNTRIES).map((c) => ({
  code: c.code,
  name: c.name,
}));
